/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2014-04-15 19:10:39 UTC)
 * on 2014-05-09 at 11:35:55 UTC 
 * Modify at your own risk.
 */

package com.appspot.otmopo3smssave.smssync.model;

/**
 * Greeting that stores a message.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the smssync. For a detailed explanation see:
 * <a href="http://code.google.com/p/google-http-java-client/wiki/JSON">http://code.google.com/p/google-http-java-client/wiki/JSON</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class SmsApiDatamodelSms extends com.google.api.client.json.GenericJson {

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key("date_received")
  private java.lang.String dateReceived;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key("ds_key")
  private java.lang.String dsKey;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key("from_number")
  private java.lang.String fromNumber;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key("loc_lat")
  private java.lang.String locLat;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key("loc_long")
  private java.lang.String locLong;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key("sms_text")
  private java.lang.String smsText;

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getDateReceived() {
    return dateReceived;
  }

  /**
   * @param dateReceived dateReceived or {@code null} for none
   */
  public SmsApiDatamodelSms setDateReceived(java.lang.String dateReceived) {
    this.dateReceived = dateReceived;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getDsKey() {
    return dsKey;
  }

  /**
   * @param dsKey dsKey or {@code null} for none
   */
  public SmsApiDatamodelSms setDsKey(java.lang.String dsKey) {
    this.dsKey = dsKey;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getFromNumber() {
    return fromNumber;
  }

  /**
   * @param fromNumber fromNumber or {@code null} for none
   */
  public SmsApiDatamodelSms setFromNumber(java.lang.String fromNumber) {
    this.fromNumber = fromNumber;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getLocLat() {
    return locLat;
  }

  /**
   * @param locLat locLat or {@code null} for none
   */
  public SmsApiDatamodelSms setLocLat(java.lang.String locLat) {
    this.locLat = locLat;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getLocLong() {
    return locLong;
  }

  /**
   * @param locLong locLong or {@code null} for none
   */
  public SmsApiDatamodelSms setLocLong(java.lang.String locLong) {
    this.locLong = locLong;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getSmsText() {
    return smsText;
  }

  /**
   * @param smsText smsText or {@code null} for none
   */
  public SmsApiDatamodelSms setSmsText(java.lang.String smsText) {
    this.smsText = smsText;
    return this;
  }

  @Override
  public SmsApiDatamodelSms set(String fieldName, Object value) {
    return (SmsApiDatamodelSms) super.set(fieldName, value);
  }

  @Override
  public SmsApiDatamodelSms clone() {
    return (SmsApiDatamodelSms) super.clone();
  }

}
